Repository PrestaShop/docs, pull requests merged in 2021-08, with the labels that each got.

#1113 Update development environment doc for 8.0
  basics/installation/localhost.md
Labels: 8.x

#1112 Update system requirements for PS 8
  basics/installation/system-requirements.md
Labels: 8.x

#1116 Update architecture introduction for PS 8
  development/architecture/introduction.md
Labels: 8.x

#1117 Update file structure for PS 8
  development/architecture/file-structure/_index.md
  development/architecture/file-structure/understanding-src-folder.md
Labels: 8.x

#1111 Fix number of native modules
  basics/introduction.md
Labels: 8.x, Needs backport

#1077 Fixed hook locations of twig files
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1121 Remove weight from component pages so that they are sorted alphabetically
  development/components/back-office-help-sidebar.md
  development/components/configuration/_index.md
  development/components/global-components.md
Labels: 1.7.x, Backported

#1122 Remove weight from component pages so that they are sorted alphabetically
  development/components/back-office-help-sidebar.md
  development/components/configuration/_index.md
  development/components/global-components.md
Labels: 8.x

#1120 Update node version compatibility on 8.x documentation
  development/compile-assets.md
Labels: 8.x

#1127 Update good-practices.md
  modules/creation/good-practices.md
Labels: 1.7.x

#1128 Update tools-for-theme-designers.md
  themes/getting-started/tools-for-theme-designers.md
Labels: Needs backport, 1.7.x

#1130 Add a missing s to a sentence
  themes/getting-started/tools-for-theme-designers.md
Labels: 8.x, Backported
