Repository PrestaShop/docs, pull requests merged in 2021-10, with the labels that each got.

#1159 Update npm versions needed
  development/compile-assets.md
Labels: 8.x

#1055 Precise nodejs version, how to switch and node-gyp dependency on Windows
  development/compile-assets.md
Labels: Needs backport, 1.7.x

#1160 Typo correction
  scale/_index.md
Labels: 1.7.x

#1162 typos
  development/architecture/domain/domain-services.md
Labels: 8.x

#1161 fix 2 tiny typo
  development/architecture/domain/domain-services.md
Labels: 1.7.x

#1155 Fix Classic translation system documentation
  modules/creation/module-translation/classic-system.md
Labels: 1.7.x

#1166 1.7.x nginx
  basics/installation/nginx.md
  scale/webservers/nginx.md
Labels: 1.7.x
