Repository PrestaShop/docs, pull requests merged in 2021-12, with the labels that each got.

#1235 Fix syntax error in relref
  development/components/grid/columns-reference/toggle.md
Labels: 1.7.x

#1232 Fix the command-line to launch the test suite
  contribute/contribute-pull-requests/contribute_using_docker.md
Labels: 1.7.x

#1242 Update overrides.md
  modules/concepts/overrides.md
Labels: 1.7.x

#1243 Removing 'Selling your modules' from docs
  modules/sell/_index.md
  modules/sell/technical-tools.md
  modules/sell/techvalidation-checklist.md
  modules/sell/techvalidation-keysteps.md
Labels: 8.x

#1241 Fix missing curly brackets in relref
  development/components/grid/columns-reference/toggle.md
Labels: 8.x

#1240 fix some typos
  themes/reference/templates/templates-layouts.md
Labels: Needs backport, 1.7.x

#1197 Add actionPresent Hooks
  modules/concepts/hooks/list-of-hooks.md
Labels: Needs backport, 1.7.x

#1239 Fix command-line to launch the test suite with docker
  contribute/contribute-pull-requests/contribute_using_docker.md
Labels: 8.x

#1248 Fix "chmod" syntax in installation DevDocs
  basics/installation/localhost.md
Labels: 8.x

#1250 Remove actionValidateOrderAfter from hooks listing
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1249 Improve actionValidateOrderAfter doc, adding missing var and since info
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1189 Add deprecated tag + add actionGetProductPropertiesAfterUnitPrice hook
  modules/concepts/hooks/list-of-hooks.md
Labels: 1.7.x

#1246 Backport PR 1097 and remove some 1.7.x mentions
  modules/concepts/controllers/admin-controllers/_index.md
Labels: 8.x

#1244 Migrate tests-legacy directory to tests directory
  development/architecture/migration-guide/testing/behat.md
  development/architecture/migration-guide/testing/unit.md
  testing/how-to-launch-tests.md
  testing/introduction.md
Labels: 8.x, Version specific

#1253 Refer to versions table of nodejs inside getting started
  themes/getting-started/tools-for-theme-designers.md
Labels: 1.7.x, Backported

#1251 Improved behat docs for new optimizations
  development/architecture/migration-guide/testing/behat.md
  testing/how-to-create-your-own-behat-tests.md
Labels: 8.x, Version specific, waiting for rebase

#1255 Update product_suppliers.md
  webservice/resources/product_suppliers.md
Labels: 1.7.x

#1245 Adds an example to override a front/admin controller inside a module
  modules/concepts/overrides.md
Labels: 8.x

#1257 Add displayAdminOrderCreateExtraButtons hook
  modules/concepts/hooks/list-of-hooks.md
Labels: 1.7.x

#1258 Add displayAdminOrderCreateExtraButtons hook
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1259 Add Module dependencies attribute
  modules/concepts/module-class/_index.md
Labels: 8.x

#1252 Document configuration console command
  development/components/configuration/_index.md
  development/components/console/prestashop-config.md
Labels: 8.x

#1256 Update twig templates override in modules
  modules/concepts/templating/admin-views.md
Labels: 8.x

#1260 `updateProduct` & `updatedProduct` events should have different descriptions
  themes/reference/javascript-events/_index.md
Labels: Needs backport, 1.7.x

#1262 Proper way to include Grid components in js context
  development/components/global-components.md
Labels: 1.7.x
