Repository PrestaShop/docs, pull requests merged in 2021-09, with the labels that each got.

#1131 Explain where data need to be stored in module's context
  modules/creation/good-practices.md
Labels: 8.x

#1119 Explain how to navigate prestashop
  basics/introduction.md
Labels: 8.x

#1134 Additional info in the webservice example
  webservice/tutorials/advanced-use/additional-list-parameters.md
Labels: 1.7.x, Backported

#1138 Add Devdocs site update badge in README
  README.md
Labels: 8.x

#1136 Prohibition to use global variables for PS 8
  modules/creation/good-practices.md
Labels: 8.x

#1143 Use ffittschen/pr-branch-labeler to automatically add labels 1.7.x and 8.x
  .github/pr-branch-labeler.yml
  .github/workflows/pr-branch-labeler.yml
Labels: Needs backport

#1144 Use ffittschen/pr-branch-labeler (1.7.x)
  .github/pr-branch-labeler.yml
  .github/workflows/pr-branch-labeler.yml
Labels: 1.7.x

#1149 webservice lib : wrong autoload file path
  webservice/tutorials/prestashop-webservice-lib/setup-library.md
Labels: 1.7.x

#1150 Webservice lib : fix wrong autoload file path 8.x
  webservice/tutorials/prestashop-webservice-lib/setup-library.md
Labels: 8.x, Backported

#1153 Fix typo in software licenses page
  contribute/contribution-guidelines/compatible-licenses.md
Labels: 8.x

#1048 Create your own distribution
  src/content/1.7/basics/deployment/_index.md
  src/content/1.7/basics/deployment/distribution.md
Labels: 8.x

#1154 Fix Position location
  modules/creation/displaying-content-in-front-office.md
Labels: 1.7.x

#1158 Backport PR 1154 to 8.x
  modules/creation/displaying-content-in-front-office.md
Labels: 8.x, Backported
