Repository PrestaShop/docs, pull requests merged in 2021-11, with the labels that each got.

#1205 fix docker hub links
  modules/testing/resources.md
Labels: 1.7.x

#1185 Improve HelperOptions doc
  development/components/helpers/helperoptions.md
Labels: 1.7.x

#1206 fix links to docker hub
  modules/testing/resources.md
Labels: 8.x

#1207 Improve JS toggle doc
  development/components/grid/columns-reference/toggle.md
Labels: 1.7.x

#1194 Update broken 404 links to github points 1.7.6.x -> 1.7.8.0
  modules/concepts/controllers/front-controllers.md
Labels: 1.7.x

#1214 Color picker is coming to v8, not 1.7.9
  development/components/global-components.md
Labels: 8.x

#1215 Color picker won't be available in 1.7
  development/components/global-components.md
Labels: 1.7.x

#1212 Improve HelperOptions doc
  development/components/helpers/helperoptions.md
Labels: 8.x

#1210 Redirect maintainer's guide to the project's site (Backport #1201)
  project/maintainers-guide/_index.md
  project/maintainers-guide/how-to-become-a-maintainer.md
  project/maintainers-guide/license.md
  project/maintainers-guide/processes.md
  project/maintainers-guide/release-a-native-PS-module.md
  project/maintainers-guide/releasing-prestashop/_index.md
  project/maintainers-guide/releasing-prestashop/create-build.md
  project/maintainers-guide/releasing-prestashop/final-steps.md
  project/maintainers-guide/releasing-prestashop/preliminary-tasks.md
  project/maintainers-guide/releasing-prestashop/release-publicly.md
  project/maintainers-guide/reviewing-pull-requests.md
  project/maintainers-guide/summary-github-lifecycle.md
Labels: 1.7.x, Backported

#1211 Move distribution doc into the appropriate directory and improve it
  basics/deployment/_index.md
  basics/deployment/distribution.md
  src/content/1.7/basics/deployment/distribution.md
Labels: 8.x, Version specific

#1213 Document changes to the assets loading and a few improvements
  themes/getting-started/asset-management/_index.md
Labels: 8.x, Version specific

#1218 Replaced deprecated method
  modules/concepts/controllers/front-controllers.md
Labels: Needs backport, 1.7.x

#1216 Precise version for grid hooks
  modules/concepts/hooks/list-of-hooks.md
Labels: Needs backport

#1219 Update how-to-handle-multi-lang-doctrine-entity.md
  modules/concepts/doctrine/how-to-handle-multi-lang-doctrine-entity.md
Labels: 1.7.x

#1223 Update how-to-handle-multi-lang-doctrine-entity.md
  modules/concepts/doctrine/how-to-handle-multi-lang-doctrine-entity.md
Labels: 8.x

#1222 Fix typo in heading
  contribute/contribute-pull-requests/create-pull-request.md
Labels: 8.x

#1221 Fixed the link that points to the correct phpCs configuration file
  development/coding-standards/_index.md
Labels: 8.x, Version specific

#1217 Explain supported branches and regressions better
  contribute/contribution-guidelines/_index.md
  contribute/contribution-guidelines/supported-branches.md
Labels: 8.x

#1220 Add documentation for debug command
  development/components/console/prestashop-debug.md
Labels: 8.x, Version specific

#1225 Update localhost.md
  basics/installation/localhost.md
Labels: 8.x

#1227 Fix version of the prestashop where you can use new grid hooks
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1230 Fix hookActionFrontControllerSetVariables smarty exemple
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1208 Fixed links to ModuleFrontController.php
  modules/concepts/controllers/front-controllers.md
Labels: 8.x, Backported

#1226 Replaced deprecated method
  modules/concepts/controllers/front-controllers.md
Labels: 8.x, Backported

#1229 Fix assign custom slip vars
  modules/concepts/pdf.md
Labels: 8.x, Backported

#1228 Improve JS toggle doc
  development/components/grid/columns-reference/toggle.md
Labels: 8.x, Backported

#1203 Add "Override a module"
  modules/concepts/overrides.md
Labels: 1.7.x

#1237 Add "Override a module"
  modules/concepts/overrides.md
Labels: 8.x

#1234 document how to run only part of phpunit tests
  testing/how-to-launch-tests.md
Labels: 8.x
