Repository PrestaShop/docs, pull requests merged in 2022-02, with the labels that each got.

#1283 Improve commit guidelines
  contribute/contribution-guidelines/_index.md
Labels: 8.x

#1284 adding OFL for fonts to the list.
  contribute/contribution-guidelines/compatible-licenses.md
Labels: Needs backport, 1.7.x

#1291 Improve distribution page
  basics/deployment/distribution.md
Labels: 8.x

#1292 Remove mention to Addons in theme section
  themes/distribution/_index.md
Labels: 8.x

#1293 Remove mentions to Addons in use-autoupgrade-module
  basics/keeping-up-to-date/use-autoupgrade-module.md
Labels: 8.x

#1294 Delete deprecated reference to automated tests on themes forlder
  themes/distribution/testing.md
Labels: 8.x, Needs backport

#1290 Fix link 404 on ressource test page
  modules/testing/resources.md
Labels: 1.7.x

#1296 Backport "Import commit guidelines" to 1.7.x
  contribute/contribution-guidelines/_index.md
Labels: 1.7.x, Backported

#1299 Backport PR 1260 to 8.x
  themes/reference/javascript-events/_index.md
Labels: 8.x, Backported

#1295 Backport PR 1294 to 1.7.x
  themes/distribution/testing.md
Labels: 1.7.x, Backported

#1288 Switch AND to OR
  webservice/getting-started.md
Labels: 8.x

#1289 Switch AND to OR
  webservice/getting-started.md
Labels: 1.7.x

#1302 Backport PR 1290 to 8.x
  modules/testing/resources.md
Labels: 8.x, Backported

#1277 Fix hook actionPresentCart parameter indentation
  modules/concepts/hooks/list-of-hooks.md
Labels: 1.7.x

#1303 Fix path to .eslintrc.js file
  themes/getting-started/guidelines.md
Labels: 8.x

#1305 The list of Smarty variables deserve a title
  modules/creation/displaying-content-in-front-office.md
Labels: 8.x

#1306 Fix `DbQuery` class `limit` method signature.
  development/components/database/dbquery.md
Labels: 8.x

#1304 Remove the root note, the file could be everywhere inside the module
  modules/testing/resources.md
Labels: 8.x
