Repository PrestaShop/docs, pull requests merged in 2022-07, with the labels that each got.

#1396 Fix old link to https://cs.sensiolabs.org/
  development/coding-standards/_index.md
Labels: 1.7.x

#1389 Fix minor typos for Modules section
  modules/creation/adding-configuration-page.md
  modules/creation/module-translation/new-system.md
Labels: 1.7.x, Backported

#1403 Fix minor typos for Modules section
  modules/creation/adding-configuration-page.md
  modules/creation/module-translation/new-system.md
Labels: 8.x

#1397 Fix link to PHP CS Fixer
  development/coding-standards/_index.md
Labels: 8.x

#1394 Fix catalog tabs parent
  modules/concepts/controllers/admin-controllers/tabs.md
Labels: 8.x, Needs backport

#1406 Fix for the correct hook name and twig file's path
  modules/concepts/hooks/use-hooks-on-modern-pages.md
Labels: 8.x

#1409 Wrap bash command in bash block
  basics/installation/localhost.md
Labels: 8.x

#1416 Backport of PR1409
  basics/installation/localhost.md
Labels: 1.7.x

#1414 Add Blockwishlist and remove Welcome
  development/native-modules/_index.md
Labels: 8.x

#1415 Add blockwishlist to native module
  development/native-modules/_index.md
Labels: 1.7.x

#1420 Change .js by .ts for links
  development/page-reference/back-office/order/add-new-order/_index.md
Labels: 8.x

#1418 Fix 404 link and typo
  development/page-reference/back-office/order/view-order/refunds/_index.md
Labels: 8.x

#1419 Fix 404 link
  development/page-reference/back-office/order/view-order/refunds/_index.md
Labels: 1.7.x

#1413 Update jQuery version
  themes/getting-started/theme-organization.md
Labels: 8.x

#1417 Fix new hooks link
  development/page-reference/back-office/order/view-order/_index.md
Labels: 8.x

#1422 fix: update XAMPP broken link
  basics/installation/localhost.md
Labels: 8.x, Needs backport

#1423 fix: update XAMPP broken link 1.7.x
  basics/installation/localhost.md
Labels: 1.7.x
