Repository PrestaShop/docs, pull requests merged in 2022-08, with the labels that each got.

#1378 Link for Clone the repository using Git
  basics/installation/localhost.md
Labels: 1.7.x

#1428 Add missing char; Replace newer release image; Add needed link
  basics/installation/img/Prestashop_1.7.8.6_release.png
  basics/installation/localhost.md
Labels: 8.x, Backported

#1431 Update introduction.md
  basics/introduction.md
Labels: 8.x

#1407 Update introduction.md
  basics/introduction.md
Labels: 1.7.x, Backported

#1433 Fix broken image link after PR 1428 merged
  basics/installation/localhost.md
Labels: 8.x

#1443 Backport of 1442
  development/architecture/cache.md
  development/architecture/domain/value_objects.md
  development/architecture/migration-guide/forms/settings-forms.md
Labels: 1.7.x

#1427 Documentation for BC Breaks and changes in 8.0
  modules/concepts/hooks/list-of-hooks.md
  modules/core-updates/8.0.md
Labels: 8.x

#1444 Update sql link, ts extensions, and branch links
  development/database/structure.md
  development/page-reference/back-office/order/add-new-order/_index.md
  development/page-reference/back-office/order/view-order/_index.md
Labels: 8.x

#1454 Update theme argument description
  development/components/console/prestashop-theme-enable.md
Labels: 8.x, Needs backport

#1456 Update theme argument description
  development/components/console/prestashop-theme-enable.md
Labels: 1.7.x

#1452 Javascript file extension and import path changes since PS 8.0.0
  development/components/grid/tutorials/extend-grid-with-javascript.md
Labels: 8.x

#1459 Remove tests-legacy
  testing/introduction.md
Labels: 8.x, Version specific

#1453 Remove extra -v and update ouptput of classname modifier
  development/components/smarty-extensions/_index.md
Labels: 8.x, Needs backport

#1457 Remove extra -v of classname modifier output
  development/components/smarty-extensions/_index.md
Labels: 1.7.x

#1461 Fix a broken ref and some typos
  development/mail.md
  development/multistore/configuration-forms/_index.md
  development/upgrade-module/upgrade-module-internal-behavior.md
  development/upgrade-module/upgrade-process-steps.md
  modules/sample-modules/order-pages-new-hooks/_index.md
Labels: 8.x

#1462 Backport of PR1461
  development/multistore/configuration-forms/_index.md
  development/upgrade-module/upgrade-module-internal-behavior.md
  development/upgrade-module/upgrade-process-steps.md
Labels: 1.7.x

#1458 Add latest JavaScript components
  development/components/global-components.md
Labels: 8.x, Version specific

#1460 Use the @Prestashop notation
  development/components/form/form-theme/form-theme.md
Labels: 8.x, Version specific

#1464 Switch links to 8.0, Strings changed since 1.7, Correct hooks name
  modules/creation/_index.md
  modules/creation/displaying-content-in-front-office.md
  modules/creation/external-services.md
  modules/creation/good-practices.md
  modules/creation/tutorial.md
Labels: 8.x

#1466 Backport of PR1464
  modules/creation/displaying-content-in-front-office.md
  modules/creation/tutorial.md
Labels: 1.7.x

#1468 Wrong path in the folders for SF migrated pages in introduction.md
  basics/introduction.md
Labels: 8.x

#1332 Add hint about var/cache folder for upgrade
  basics/keeping-up-to-date/upgrade.md
Labels: 1.7.x
