Repository PrestaShop/docs, pull requests merged in 2022-12, with the labels that each got.

#1575 Move articles to .org
  contribute/_index.md
  contribute/contribute-by-testing-pull-requests.md
  contribute/contribute-reporting-issues.md
  contribute/contribution-process/how-issues-are-sorted.md
  contribute/img/github-create-account.png
  contribute/img/github-issue-editor.png
  contribute/img/github-new-issue.png
  contribute/img/github-select-issue-type.png
  contribute/img/vagrant/build-failed.png
  contribute/img/vagrant/invalid-php-version.png
  contribute/img/vagrant/run-script.png
  contribute/img/vagrant/script-ended-successful.png
Labels: 8.x

#1576 Legacy controller execution flow : Changed a png diagram to a mermaid one to improve searchability and maintainability
  development/architecture/legacy/img/legacy-controller-flow.png
  development/architecture/legacy/legacy-controllers.md
Labels: 8.x, Needs backport

#1278 Please clarify the correct way to autoload Commands added by modules
  faq/modules.md
  modules/concepts/commands.md
Labels: Needs backport, 1.7.x

#1581 Update _index.md
  modules/concepts/services/_index.md
Labels: 8.x

#1580 Fix typo on `install-from-cli.md`
  basics/installation/install-from-cli.md
Labels: 8.x

#1574 Improve order lifecycle documentation
  development/orders-lifecycle/_index.md
Labels: 8.x

#1583 Update Doctrine version, switch to 8.x branch
  modules/concepts/doctrine/_index.md
  modules/concepts/doctrine/how-to-handle-multi-lang-doctrine-entity.md
Labels: 8.x

#1586 Move example from PululuK on actionValidateOrder hook
  modules/concepts/hooks/list-of-hooks/_index.md
  modules/concepts/hooks/list-of-hooks/actionValidateOrder.md
  modules/sample-modules/example-hooks/_index.md
  modules/sample-modules/example-hooks/actionValidateOrder.md
Labels: 8.x

#1585 Add key for git info
  .github/workflows/build.yml
Labels: 8.x

#1587 Add example flag on ActionValidateOrder
  modules/concepts/hooks/list-of-hooks/actionValidateOrder.md
Labels: 8.x
