Repository PrestaShop/docs, pull requests merged in 2022-04, with the labels that each got.

#1330 Update mobile actions
  development/components/console/prestashop-module.md
Labels: 8.x

#1339 Add actionOrderStatusPostUpdate hooks new params
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1344 Give an example on how to handle translation of Javascript strings.
  development/internationalization/translation/using-the-translator.md
Labels: Needs backport, 1.7.x

#1346 Unindent code block
  development/internationalization/translation/using-the-translator.md
Labels: 1.7.x

#1345 Example on how to handle translation of Javascript strings (backport
  development/internationalization/translation/using-the-translator.md
Labels: 8.x, Backported

#1349 minor typo
  development/components/hook/register-new-hook.md
Labels: 8.x, Needs backport

#1347 Backport PR 1119
  basics/introduction.md
Labels: 1.7.x, Backported

#1348 Fix module mail templates example
  modules/concepts/mail-templates/add-a-layout-from-module.md
  modules/concepts/mail-templates/add-a-theme-from-module.md
  modules/concepts/mail-templates/add-layout-variables-from-module.md
  modules/concepts/mail-templates/apply-transformation-from-module.md
  modules/concepts/mail-templates/extend-a-layout-from-module.md
Labels: 8.x, Needs backport

#1343 Add related PR instructions
  contribute/contribution-guidelines/pull-requests.md
Labels: 8.x

#1358 Backport 1313
  modules/concepts/controllers/front-controllers.md
Labels: 8.x, Backported

#1356 Backport of 1303
  themes/getting-started/guidelines.md
Labels: 1.7.x, Backported

#1355 Backport 1293
  basics/keeping-up-to-date/use-autoupgrade-module.md
Labels: 1.7.x, Backported

#1354 Backport 1179
  contribute/img/pull-request-process.png
Labels: 1.7.x, Backported

#1353 Backport 1240
  themes/reference/templates/templates-layouts.md
Labels: 8.x, Backported

#1352 Backport 1180
  contribute/img/forge-accountCreated.jpg
  contribute/img/forge-createAccount.jpg
  contribute/img/forge-createIssue.jpg
  contribute/img/forge-createIssue2.jpg
Labels: 1.7.x, Backported

#1351 Backport 1183
  themes/distribution/exporting.md
Labels: 1.7.x, Backported

#1350 Backport of PR 1123
  development/components/database/objectmodel.md
Labels: 8.x, Backported

#1357 Backport 1308
  development/components/form/types-reference/formatted-textarea.md
Labels: 8.x, Backported

#1360 Update widgets.md
  modules/concepts/widgets.md
Labels: Needs backport, 1.7.x

#1361 Update hook widgets wording
  modules/concepts/widgets.md
Labels: 8.x, Backported

#1362 Update security-policy.md
  project/security-policy.md
Labels: 8.x
