Repository PrestaShop/docs, pull requests merged in 2022-09, with the labels that each got.

#1476 Fix jQuery version
  themes/reference/javascript-events/_index.md
Labels: 8.x

#1477 Update jQuery version
  themes/reference/javascript-events/_index.md
Labels: 1.7.x

#1473 Correct the folder and extension of css output
  themes/getting-started/asset-management/webpack.md
Labels: 1.7.x, Backported

#1474 Correct the folder and extension of css output
  themes/getting-started/asset-management/webpack.md
Labels: 8.x, Backported

#1463 Define missing hooks in list
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1451 More precise info about installer + notable change for the Hook component
  modules/core-updates/8.0.md
Labels: 8.x, Version specific

#1479 Improve example branch
  contribute/contribution-guidelines/_index.md
Labels: 1.7.x

#1434 Remove TextWithUnitType add UnitTypeExtension
  development/components/form/types-reference/_index.md
  development/components/form/types-reference/img/unit-type-extention.png
  development/components/form/types-reference/unit-type-extension.md
Labels: 8.x

#1482 Note about routing config during controller decoration
  modules/concepts/controllers/admin-controllers/override-decorate-controller.md
Labels: 8.x

#1481 Update tutorial typo
  modules/creation/tutorial.md
Labels: 1.7.x

#1483 Update tutorial.md - changed wording
  modules/creation/tutorial.md
Labels: 8.x, Backported

#1490 Fix code examples on grids (Backported #1341)
  development/components/grid/actions-reference/_index.md
  development/components/grid/bulk-actions-reference/_index.md
  development/components/grid/columns-reference/_index.md
  development/components/grid/columns-reference/action.md
  development/components/grid/filter-types-reference/_index.md
  development/components/grid/tutorials/work-with-bulk-actions.md
  development/components/grid/tutorials/work-with-grid-actions.md
  development/components/grid/tutorials/work-with-row-actions.md
Labels: 8.x

#1491 Fix module mail templates example, add extends (Backported #1348)
  modules/concepts/mail-templates/add-a-layout-from-module.md
  modules/concepts/mail-templates/add-a-theme-from-module.md
  modules/concepts/mail-templates/add-layout-variables-from-module.md
  modules/concepts/mail-templates/apply-transformation-from-module.md
  modules/concepts/mail-templates/extend-a-layout-from-module.md
Labels: 1.7.x

#1489 Fix DbQuery class limit method signature (Backported #1306)
  development/components/database/dbquery.md
Labels: 1.7.x

#1485 Fix wording (Backported #1383)
  development/components/helpers/helperoptions.md
Labels: 8.x

#1488 Add a title to the list of Smarty variables (Backported 1305)
  modules/creation/displaying-content-in-front-office.md
Labels: 1.7.x

#1498 Update Faceted search doc (Backported #1371)
  development/components/faceted-search.md
  development/components/faceted-search/_index.md
  development/components/faceted-search/img/facetedsearch.png
  development/components/faceted-search/inside-faceted-search-module.md
Labels: 1.7.x

#1499 Fix minor typo for MySQL and wording interrogation
  development/components/faceted-search/inside-faceted-search-module.md
Labels: 8.x

#1501 Fix typo on foreign key (Backport of #1379)
  development/architecture/file-structure/_index.md
Labels: 8.x

#1500 Addresses webservice spelling fix (Backported #1377)
  webservice/tutorials/testing-access.md
Labels: 8.x

#1495 Fix PSR issues on examples of mail templates for 1.7.x
  modules/concepts/mail-templates/add-a-layout-from-module.md
  modules/concepts/mail-templates/add-a-theme-from-module.md
  modules/concepts/mail-templates/add-layout-variables-from-module.md
  modules/concepts/mail-templates/apply-transformation-from-module.md
  modules/concepts/mail-templates/extend-a-layout-from-module.md
Labels: 1.7.x

#1492 Fix wrong url for composer.md (Backport #1367)
  modules/concepts/commands.md
Labels: 8.x

#1493 Fix wrong url for composer link - was fixed but not completely right
  modules/concepts/commands.md
Labels: 1.7.x

#1494 Fix PSR issues on examples of mail templates
  modules/concepts/mail-templates/add-a-layout-from-module.md
  modules/concepts/mail-templates/add-a-theme-from-module.md
  modules/concepts/mail-templates/add-layout-variables-from-module.md
  modules/concepts/mail-templates/apply-transformation-from-module.md
  modules/concepts/mail-templates/extend-a-layout-from-module.md
Labels: 8.x

#1480 Update reference.md
  webservice/reference.md
Labels: Needs backport, 1.7.x

#1506 Change referenced module name in facet search documentation
  development/components/faceted-search/inside-faceted-search-module.md
Labels: 8.x

#1505 Fix indentation on admin-controllers / tabs (Backport 1394)
  modules/concepts/controllers/admin-controllers/tabs.md
Labels: 1.7.x

#1496 Add hint about var/cache folder for upgrade (Backported #1332)
  basics/keeping-up-to-date/upgrade.md
Labels: 8.x

#1497 Module error with namespace Foo\Repository, change composer links (Backported #1364 + Fix)
  modules/concepts/hooks/use-hooks-on-modern-pages.md
Labels: 8.x, Backported

#1510 Remove a wrong link in democqrshooksusage module
  modules/sample-modules/grid-and-identifiable-object-form-hooks-usage.md
Labels: 8.x

#1511 Backport of PR1510
  modules/sample-modules/grid-and-identifiable-object-form-hooks-usage.md
Labels: 1.7.x

#1503 Fix naming conventions duplicate word (backport 1380)
  development/naming-conventions/_index.md
Labels: 8.x, Backported

#1504 Request to update the link to customer-manager.js (backport 1381 + 1392)
  development/page-reference/back-office/order/add-new-order/_index.md
Labels: 8.x

#1471 Fix KpiRowHook location
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x, Needs backport

#1430 Use hooks on Symfony page: new catalog-tools button for PS 1.7.6.5, switch to SF 4.4
  modules/concepts/hooks/Catalog_Products_2xml.png
  modules/concepts/hooks/Catalog_Products_dump.png
  modules/concepts/hooks/use-hooks-on-modern-pages.md
Labels: 8.x

#1475 Add sendemail=1 to order_carriers endpoint
  webservice/getting-started.md
Labels: 8.x

#1386 Introduce PATCH request into webservice API
  webservice/cheat-sheet.md
  webservice/getting-started.md
  webservice/resources/images.md
  webservice/tutorials/creating-access.md
  webservice/tutorials/prestashop-webservice-lib/setup-library.md
  webservice/tutorials/testing-access.md
Labels: 8.x, Version specific

#1507 Testing : Improving Section & Complete documentation
  contribute/contribute-pull-requests/contribute_using_docker.md
  modules/testing/resources.md
  testing/_index.md
  testing/integration-tests/_index.md
  testing/integration-tests/how-to-create-your-own-behat-tests.md
  testing/integration-tests/how-to-create-your-own-symfony-controller-tests.md
  testing/integration-tests/how-to-execute-tests.md
  testing/introduction.md
  testing/ui-tests/_index.md
  testing/ui-tests/how-to-create-your-own-ui-tests.md
  testing/ui-tests/how-to-execute-tests.md
  testing/unit-tests/_index.md
  testing/unit-tests/how-to-create-your-own-unit-tests.md
  testing/unit-tests/how-to-execute-tests.md
Labels: 8.x

#1410 Add Webservice tutorial in (Modules) extension concept section
  modules/concepts/img/articles-list.png
  modules/concepts/img/empty-articles.png
  modules/concepts/img/new-ws-resource.png
  modules/concepts/webservice/_index.md
Labels: Needs backport, 1.7.x

#1374 Revise Webservice API reference
  webservice/reference.md
Labels: Needs backport, 1.7.x

#1408 Update migration.md
  basics/keeping-up-to-date/migration.md
Labels: 8.x

#1512 Fix inconsistency link between MarkDown and HugoServer for PR 1430
  modules/concepts/hooks/use-hooks-on-modern-pages.md
Labels: 8.x

#1508 Fix references from develop to 1.7.8.0
  basics/installation/localhost.md
  contribute/contribution-guidelines/pull-requests.md
  contribute/contribution-process/how-pull-requests-are-processed.md
  development/architecture/domain/domain-services.md
  development/architecture/migration-guide/controller-routing.md
  development/architecture/migration-guide/forms/CRUD-forms.md
  development/architecture/migration-guide/forms/settings-forms.md
  development/architecture/migration-guide/hooks.md
  development/architecture/migration-guide/testing/behat.md
  development/architecture/migration-guide/validation.md
  development/architecture/modern/controller-routing.md
  development/coding-standards/_index.md
  development/components/console/context-helper.md
  development/components/global-components.md
  development/database/structure.md
  development/multistore/shop-context/_index.md
  development/page-reference/back-office/order/add-new-order/_index.md
  development/page-reference/back-office/order/view-order/_index.md
  modules/concepts/controllers/admin-controllers/route-generation.md
  modules/concepts/widgets.md
  modules/creation/good-practices.md
  modules/creation/module-translation/classic-system.md
  modules/payment/_index.md
  testing/how-to-launch-tests.md
  testing/ui-tests/_index.md
  testing/ui-tests/how-to-contribute-and-create-ui-tests.md
  themes/getting-started/guidelines.md
  themes/reference/templates/notifications.md
Labels: 1.7.x

#1470 Fix links with relfref
  modules/concepts/controllers/admin-controllers/override-decorate-controller.md
  modules/sample-modules/extending-sf-form-with-upload-image-field.md
  modules/sample-modules/order-pages-new-hooks/module-base.md
  modules/sample-modules/order-pages-new-hooks/signature-widget.md
  project/release/minor-release-lifecycle.md
  scale/benchmark/front-office.md
  themes/getting-started/guidelines.md
Labels: 8.x

#1517 Improve `webservices` create a resource example
  webservice/tutorials/prestashop-webservice-lib/create-resource.md
Labels: Needs backport, 1.7.x

#1518 Improve webservice create resource example
  webservice/tutorials/prestashop-webservice-lib/create-resource.md
Labels: 8.x

#1521 Revert "Remove unnecessary files" - two images deleted in previous PR
  modules/concepts/hooks/Catalog_Products_2xml.png
  modules/concepts/hooks/Catalog_Products_dump.png
Labels: 8.x

#1520 Backport of PR 1519
  modules/sample-modules/order-pages-new-hooks/signature-widget.md
Labels: 1.7.x

#1519 Fix some typos and syntax
  modules/sample-modules/order-pages-new-hooks/signature-widget.md
Labels: 8.x

#1523 Backport of 1522 - Fix typos in CRUD Form doc
  development/architecture/migration-guide/forms/CRUD-forms.md
Labels: 8.x

#1522 Fix typos in form crud doc
  development/architecture/migration-guide/forms/CRUD-forms.md
Labels: 1.7.x

#1524 Fixed JS Doc on UI Tests
  testing/ui-tests/how-to-create-your-own-ui-tests.md
Labels: 8.x
