Repository PrestaShop/docs, pull requests merged in 2022-11, with the labels that each got.

#1561 Create example hooks section in documentation
  modules/sample-modules/_index.md
  modules/sample-modules/example-hooks/_index.md
  modules/sample-modules/example-hooks/actionValidateOrder.md
Labels: 8.x

#1544 Move configuration into its own category & add list of configurations
  basics/deployment/_index.md
  basics/installation/_index.md
  basics/installation/configuration.md
  basics/introduction.md
  basics/keeping-up-to-date/_index.md
  contribute/documentation/shortcodes/ref.md
  development/configuration/_index.md
  development/configuration/configuring-prestashop.md
  development/configuration/list-of-settings.md
Labels: 8.x

#1568 displayHeader hook only affect Front Office pages
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1571 Fix typo in creating access page (Webservice chapter)
  webservice/tutorials/creating-access.md
Labels: 8.x

#1570 backport of PR 1568
  modules/concepts/hooks/list-of-hooks.md
Labels: 1.7.x

#1557 Improve doc for Carriers WS
  webservice/resources/carriers.md
Labels: 8.x, Needs backport

#1572 Fix typo in creating access page (Webservice chapter) - 1.7
  webservice/tutorials/creating-access.md
Labels: 1.7.x

#1573 Fix identation issues, breaks DOM/search
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x

#1531 Improve documentation of `ObjectModel`
  development/components/database/objectmodel.md
  development/img/object-model-lifecycle.png
Labels: 8.x, Needs backport

#1577 Add currency rates source
  faq/pricing.md
Labels: 8.x, Needs backport
