Repository PrestaShop/docs, pull requests merged in 2022-05, with the labels that each got.

#1372 Add hugo doc about moving pages
  contribute/documentation/how/moving-pages.md
Labels: 8.x

#1370 Add missing word
  modules/concepts/hooks/use-hooks-on-modern-pages.md
Labels: waiting for author, 1.7.x

#1377 spelling fix
  webservice/tutorials/testing-access.md
Labels: Needs backport, 1.7.x

#1376 Add missing `Column Types` docs
  development/components/grid/columns-reference/_index.md
  development/components/grid/columns-reference/color.md
Labels: 8.x

#1379 Fix wording
  development/architecture/file-structure/_index.md
Labels: Needs backport, 1.7.x

#1380 Fix `Naming conventions` wording
  development/naming-conventions/_index.md
Labels: Needs backport, 1.7.x

#1383 fix wording
  development/components/helpers/helperoptions.md
Labels: Needs backport, 1.7.x

#1382 Fix images
  development/page-reference/back-office/order/add-new-order/_index.md
Labels: Needs backport, 1.7.x

#1384 Add ColorColumn doc
  development/components/grid/columns-reference/_index.md
  development/components/grid/columns-reference/color.md
Labels: 1.7.x

#1375 Explain what files does what in form themes
  development/components/form/form-theme/form-theme.md
Labels: 1.7.x

#1371 Update Faceted search doc
  development/components/faceted-search.md
  development/components/faceted-search/_index.md
  development/components/faceted-search/img/facetedsearch.png
  development/components/faceted-search/inside-faceted-search-module.md
Labels: 8.x
