Repository PrestaShop/docs, pull requests merged in 2022-01, with the labels that each got.

#1254 Refer to nodejs compatibility table and add node 16
  development/compile-assets.md
  themes/getting-started/tools-for-theme-designers.md
Labels: 8.x

#1264 Add displayAfterTitleTag hook
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x, Needs backport

#1266 Add link to all example modules
  modules/sample-modules/_index.md
Labels: 1.7.x

#1265 Add link to all example modules
  modules/sample-modules/_index.md
Labels: 8.x

#1263 add displayAfterTitleTag hook
  modules/concepts/hooks/list-of-hooks.md
Labels: 1.7.x

#1268 fix link to symfony doc (form as service).
  development/architecture/migration-guide/forms/_index.md
Labels: 1.7.x

#1267 Changed database structure version number to the latest one
  development/database/structure.md
Labels: 1.7.x

#1269 remove anchor part of link symfony doc
  development/architecture/migration-guide/forms/_index.md
Labels: 8.x

#1271 Fix Minor typos in the documentation in update CI/CD
  modules/testing/ci-cd.md
Labels: 1.7.x

#1275 Fixed minor typos in the documentation for CI/CD
  modules/testing/ci-cd.md
Labels: 8.x
