Repository PrestaShop/docs, pull requests merged in 2022-03, with the labels that each got.

#1307 Remove the root note, the file could be everywhere inside the module
  modules/testing/resources.md
Labels: 1.7.x

#1281 Add the registerHook|unregisterHook action
  development/components/console/prestashop-module.md
Labels: 8.x, waiting for PR merge

#1282 Remove links to PrestaShop Company
  basics/introduction.md
  basics/keeping-up-to-date/_index.md
  basics/keeping-up-to-date/migration.md
  basics/keeping-up-to-date/upgrade.md
  development/architecture/introduction.md
  development/upgrade-module/_index.md
  faq/i-need-help.md
  modules/introduction.md
  modules/sample-modules/order-pages-new-hooks/additional-action-buttons.md
  themes/getting-started/setting-up-your-local-environment.md
  themes/getting-started/theme-yml.md
Labels: 8.x

#1309 Backport 1272 to 8.x
  development/architecture/migration-guide/forms/CRUD-forms.md
Labels: 8.x, Backported

#1308 Adding information for using TinyMCE editor and FormattedTextareaType with prestashop UI kit and twig form
  development/components/form/types-reference/formatted-textarea.md
Labels: 1.7.x

#1310 Update translation domains page
  development/internationalization/translation/img/Admin_mindmap.png
  development/internationalization/translation/img/Emails_mindmap.png
  development/internationalization/translation/img/Modules_mindmap.png
  development/internationalization/translation/img/Shop_mindmap.png
  development/internationalization/translation/pdf/Admin_legend.pdf
  development/internationalization/translation/pdf/Shop_legend.pdf
  development/internationalization/translation/translation-domains.md
Labels: 1.7.x

#1313 fix(doc): updated modulefrontcontroller doc
  modules/concepts/controllers/front-controllers.md
Labels: 1.7.x

#1315 Add all notable changes in 8.0
  modules/core-updates/8.0.md
Labels: 8.x

#1334 Document removed endpoints
  modules/core-updates/8.0.md
Labels: 8.x

#1279 Fix usage of underscores in new translation system page
  modules/creation/module-translation/new-system.md
Labels: Needs backport, 1.7.x

#1335 Add child section to Scale
  scale/_index.md
Labels: 8.x

#1337 Doc possibility to load PHP / XML files for modules services
  modules/concepts/services/_index.md
Labels: 8.x

#1338 Fix minor typos
  modules/concepts/services/_index.md
Labels: 1.7.x
