Repository PrestaShop/docs, pull requests merged in 2022-10, with the labels that each got.

#1529 Update project hostname
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  development/coding-standards/_index.md
  modules/concepts/hooks/use-hooks-on-modern-pages.md
Labels: 8.x

#1530 Update project hostname
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  development/coding-standards/_index.md
  development/components/grid/tutorials/extend-grid-with-javascript.md
  modules/core-updates/1.6-1.7.md
  modules/sample-modules/extending-sf-form-with-upload-image-field.md
  modules/sample-modules/order-pages-new-hooks/_index.md
  modules/sample-modules/order-pages-new-hooks/module-base.md
  modules/sample-modules/order-pages-new-hooks/signature-widget.md
  modules/sell/technical-tools.md
  project/release/minor-release-lifecycle.md
  scale/benchmark/front-office.md
  themes/getting-started/guidelines.md
Labels: 1.7.x, Backported

#1526 Update module names, template code for PS 1.7
  themes/reference/overriding-modules.md
Labels: 8.x

#1527 Backport of PR1526
  themes/reference/overriding-modules.md
Labels: 1.7.x

#1533 Update classic theme changes in PrestaShop 8
  themes/reference/templates/notifications.md
Labels: 8.x

#1536 Fix release lifecycle links (1.7.x backport)
  project/release/minor-release-lifecycle.md
  project/release/patch-release-lifecycle.md
Labels: 1.7.x

#1542 Change urls from build.prestashop.com to build.prestashop-project.org for 1.7.x
  contribute/contribute-pull-requests/_index.md
  contribute/contribute-pull-requests/contribute_using_localhost.md
  contribute/contribution-guidelines/_index.md
  contribute/contribution-process/how-issues-are-sorted.md
  contribute/contribution-process/how-pull-requests-are-processed.md
  development/architecture/introduction.md
  development/architecture/migration-guide/strategy.md
  development/architecture/migration-guide/templating-with-twig.md
  development/page-reference/back-office/order/view-order/refunds/_index.md
  development/uikit.md
  modules/introduction.md
  modules/sell/technical-tools.md
  project/release/minor-release-lifecycle.md
  project/release/patch-release-lifecycle.md
  themes/getting-started/setting-up-your-local-environment.md
Labels: 1.7.x

#1538 Add install method from cli in doc
  basics/installation/install-from-cli.md
Labels: 8.x

#1549 Change referenced module name - backport 1506
  development/components/faceted-search/inside-faceted-search-module.md
Labels: 1.7.x

#1548 Update instructions on how to fill PR. Backport of #1528
  contribute/contribution-guidelines/pull-requests.md
Labels: 8.x

#1547 Install module from cli and clean doc - Backport of 1534
  modules/creation/tutorial.md
Labels: 1.7.x

#1546 Install from cli documentation - Backport of 1538
  basics/installation/install-from-cli.md
Labels: 1.7.x

#1550 Update webservice reference.md, fix stock_availables methods - Backport 1480
  webservice/reference.md
Labels: 8.x

#1552 Fix KpiRowHook location - backport 1471
  modules/concepts/hooks/list-of-hooks.md
Labels: 1.7.x

#1551 Add doc about sendemail on webservices / order_carriers - Backport 1475
  webservice/getting-started.md
Labels: 1.7.x

#1555 Re-order items, fix minor typo in core changes for 8.x
  modules/core-updates/8.0.md
Labels: 8.x

#1553 Module extension : webservices - Backport 1410
  modules/concepts/img/articles-list.png
  modules/concepts/img/empty-articles.png
  modules/concepts/img/new-ws-resource.png
  modules/concepts/webservice/_index.md
Labels: 8.x

#1556 Documentation fixes
  basics/keeping-up-to-date/migration.md
  contribute/contribution-guidelines/pull-requests.md
  contribute/contribution-process/how-pull-requests-are-processed.md
  development/architecture/domain/domain-exceptions.md
  development/architecture/file-structure/_index.md
  development/architecture/file-structure/understanding-src-folder.md
Labels: 8.x

#1554 Fix versions of guzzle and smarty, and improve templates doc
  modules/creation/external-services.md
  themes/reference/templates/templates-layouts.md
Labels: 8.x

#1559 Does not use deprecated/alias hook name
  modules/carrier/_index.md
Labels: 8.x

#1560 getting-started.md grammar mistake corrected
  webservice/getting-started.md
Labels: Needs backport, 1.7.x

#1558 Add a doc about Module Self Configurator feature
  modules/configure-with-cli.md
Labels: 8.x, Needs backport

#1564 Change version 1.7 of doc to previous
  _index.md
Labels: 1.7.x

#1563 Change current version of v8 doc to current
  _index.md
Labels: 8.x

#1566 Backport of #1565
  basics/installation/configuration.md
  basics/installation/localhost.md
  basics/keeping-up-to-date/migration.md
  contribute/contribute-pull-requests/contribute_using_localhost.md
  development/components/back-office-help-sidebar.md
  faq/i-need-help.md
  modules/creation/good-practices.md
Labels: 1.7.x

#1565 Using prestashop-project.org links instead of prestashop.com
  basics/installation/configuration.md
  basics/installation/localhost.md
  basics/keeping-up-to-date/migration.md
  contribute/contribute-pull-requests/contribute_using_localhost.md
  development/components/back-office-help-sidebar.md
  faq/i-need-help.md
  modules/creation/good-practices.md
Labels: 8.x, Backported

#1567 Add hook dispatch methods in symfony controllers, and in twig templates
  modules/concepts/hooks/_index.md
  modules/concepts/hooks/list-of-hooks.md
Labels: 8.x, Needs backport
