Repository PrestaShop/docs, pull requests merged in 2022-06, with the labels that each got.

#1387 Fix minor typo and path order
  modules/concepts/hooks/use-hooks-on-modern-pages.md
Labels: 1.7.x

#1388 Add info about the undocumented hideTabs options
  development/components/form/types-reference/translatable.md
Labels: 8.x

#1381 Request to update the link to customer-manager.js
  development/page-reference/back-office/order/add-new-order/_index.md
Labels: Needs backport, 1.7.x

#1333 Documented BC for PR #27890 (core repository)
  modules/core-updates/8.0.md
Labels: 8.x, waiting for PR merge

#1393 Add php 8.1 support
  basics/installation/system-requirements.md
Labels: 8.x

#1395 Revert "Merge pull request #1333 from marsaldev/8.x"
  modules/core-updates/8.0.md
Labels: 8.x

#1400 update broken link
  themes/getting-started/guidelines.md
Labels: 8.x

#1399 update broken link
  themes/getting-started/guidelines.md
Labels: 1.7.x

#1398 Remove extraCarrier note, as it's deprecated since 1.7.0 and not used
  modules/carrier/_index.md
Labels: 8.x
