Repository PrestaShop/docs, pull requests merged in 2023-04, with the labels that each got.

#1638 RenderForm / RenderList search items
  development/components/helpers/helperform.md
  development/components/helpers/helperlist.md
Labels: 8.x

#1637 Document Locale component (formatPrice / formatNumber)
  development/components/context.md
  development/components/locale.md
Labels: 8.x

#1639 Update `HelperOptions` documentation
  development/components/helpers/helperoptions.md
Labels: 1.7.x

#1623 Document PR30588 - services configurations priority
  modules/concepts/services/_index.md
  modules/core-updates/8.1.md
Labels: 8.x

#1644 Template display.tpl must extend page.tpl
  modules/creation/displaying-content-in-front-office.md
Labels: 8.x

#1643 Document new product page extendability
  modules/concepts/hooks/list-of-hooks/action<FormName>FormBuilderModifier.md
  modules/concepts/hooks/list-of-hooks/actionAfterUpdate<FormName>FormHandler.md
  modules/core-updates/8.1.md
  modules/sample-modules/extend-product-page.md
  modules/sample-modules/img/new-product-form/seo-custom-field.png
  modules/sample-modules/img/old-product-form/seo-custom-field.png
Labels: 8.x

#1646 Bad relativePath
  modules/creation/displaying-content-in-front-office.md
Labels: 8.x

#1611 Refresh upgrade guide
  basics/keeping-up-to-date/_index.md
  basics/keeping-up-to-date/backup.md
  basics/keeping-up-to-date/img/image38.png
  basics/keeping-up-to-date/migration.md
  basics/keeping-up-to-date/upgrade-module/_index.md
  basics/keeping-up-to-date/upgrade-module/channels.md
  basics/keeping-up-to-date/upgrade-module/img/upgrade-process.png
  basics/keeping-up-to-date/upgrade-module/upgrade-cli.md
  basics/keeping-up-to-date/upgrade-module/upgrade-module-internal-behavior.md
  basics/keeping-up-to-date/upgrade-module/upgrade-process-steps.md
  basics/keeping-up-to-date/upgrade.md
  basics/keeping-up-to-date/use-autoupgrade-module.md
  development/upgrade-module/_index.md
  development/upgrade-module/upgrade-cli.md
  development/upgrade-module/upgrade-process-steps.md
Labels: 8.x

#1647 Example implementation of hookActionModifyFrontendSitemap
  modules/concepts/hooks/list-of-hooks/actionModifyFrontendSitemap.md
Labels: 8.x

#1645 PrestaShopCollection component
  development/components/database/prestashopcollection.md
Labels: 8.x, Needs backport

#1652 Improve homepage of Devdocs : Main categories icons, and flags to display pages on homepage
  .github/workflows/build.yml
  basics/_index.md
  basics/deployment/_index.md
  basics/installation/_index.md
  basics/installation/localhost.md
  basics/installation/system-requirements.md
  basics/introduction.md
  basics/keeping-up-to-date/_index.md
  contribute/_index.md
  contribute/contribute-by-testing-pull-requests.md
  contribute/contribute-pull-requests/_index.md
  contribute/contribute-reporting-issues.md
  contribute/contribution-guidelines/_index.md
  contribute/contribution-process/_index.md
  contribute/documentation/_index.md
  development/_index.md
  development/architecture/_index.md
  development/components/_index.md
  development/components/hook/subscribing-to-hook.md
  development/configuration/_index.md
  development/database/_index.md
  faq/_index.md
  faq/i-need-help.md
  faq/product.md
  faq/tips-and-tricks/_index.md
  faq/upgrade.md
  modules/_index.md
  modules/concepts/_index.md
  modules/concepts/hooks/list-of-hooks/_index.md
  modules/core-updates/_index.md
  modules/creation/_index.md
  modules/sample-modules/_index.md
  scale/_index.md
  scale/benchmark/_index.md
  scale/optimizations.md
  scale/taking-care.md
  scale/webservers/_index.md
  testing/_index.md
  themes/_index.md
  themes/distribution/_index.md
  themes/getting-started/_index.md
  themes/reference/_index.md
  webservice/_index.md
  webservice/cheat-sheet.md
  webservice/getting-started.md
  webservice/reference.md
  webservice/tutorials/_index.md
Labels: 8.x
