Repository PrestaShop/docs, pull requests merged in 2023-06, with the labels that each got.

#1673 Improve Webservices section of the documentation
  basics/keeping-up-to-date/migration.md
  development/components/database/objectmodel.md
  modules/concepts/webservice/_index.md
  modules/sample-modules/_index.md
  webservice/extend-webservice.md
  webservice/getting-started.md
  webservice/tutorials/advanced-use/_index.md
  webservice/tutorials/assets/postman01.png
  webservice/tutorials/assets/postman02.png
  webservice/tutorials/assets/postman03.png
  webservice/tutorials/prestashop-webservice-lib/_index.md
  webservice/tutorials/testing-access.md
  webservice/tutorials/testing-webservice-postman.md
Labels: 8.x, Needs backport

#1674 Update tutorial.md
  modules/creation/tutorial.md
Labels: 8.x

#1675 Fix how GitHub is spelled
  scale/benchmark/_index.md
  scale/benchmark/back-office.md
Labels: 8.x

#1677 Spell correctly GitHub
  modules/sample-modules/extending-sf-form-with-upload-image-field.md
Labels: 8.x

#1661 PrestaShop on Docker guide
  basics/installation/install-with-docker.md
  contribute/contribute-pull-requests/contribute_using_docker.md
Labels: 8.x, Needs backport

#1680 Add link to BC Break ADR
  contribute/contribution-guidelines/bc-break-promise
Labels: 8.x, Waiting for QA

#1679 Improved installation guide
  basics/installation/_index.md
  basics/installation/advanced/_index.md
  basics/installation/advanced/httpd.md
  basics/installation/advanced/install-from-cli.md
  basics/installation/advanced/nginx.md
  basics/installation/environments/docker.md
  basics/installation/environments/macos-specific.md
  basics/installation/environments/unix-specific.md
  basics/installation/environments/windows-specific.md
  basics/installation/localhost.md
  basics/installation/system-requirements.md
Labels: 8.x, Waiting for QA

#1681 Add documentation for hook actionListModules
  modules/concepts/hooks/list-of-hooks/actionListModules.md
Labels: 8.x, Waiting for QA

#1676 Module tutorial fix
  modules/concepts/hooks/list-of-hooks/displayLeftColumn.md
  modules/concepts/hooks/list-of-hooks/displayRightColumn.md
  modules/creation/displaying-content-in-front-office.md
  modules/creation/tutorial.md
Labels: 8.x

#1684 Testing : Code coverage report, reintegrate commit from tswfi, and change internal linking
  testing/unit-tests/how-to-execute-tests.md
Labels: 8.x, Waiting for QA

#1683 Document the cookie component
  development/components/context.md
  development/components/cookie.md
Labels: 8.x

#1688 Add notable changes and hook 8.1
  modules/concepts/hooks/list-of-hooks/actionLoggerLogMessage.md
  modules/concepts/hooks/list-of-hooks/actionModifyFrontendSitemap.md
  modules/concepts/hooks/list-of-hooks/displayOverrideTemplate.md
  modules/core-updates/8.1.md
Labels: 8.x, Waiting for QA

#1689 Fix domain name
  modules/concepts/mail-templates/add-a-layout-from-module.md
Labels: 1.7.x, Waiting for QA
