Repository PrestaShop/docs, pull requests merged in 2023-03, with the labels that each got.

#1621 Fix module translations - Translations in custom module files won't work
  modules/creation/module-translation/new-system.md
  modules/creation/tutorial.md
Labels: 8.x

#1622 Update link to "Get involved" page
  contribute/_index.md
Labels: 8.x

#1624 Security rules on payment modules
  modules/payment/_index.md
Labels: 8.x, Version specific

#1625 Improve search results for the hook page in Algolia
  modules/concepts/hooks/list-of-hooks/_index.md
Labels: 8.x

#1627 Improve Integration tests desc
  testing/integration-tests/_index.md
Labels: 8.x

#1628 Improve webservice doc
  webservice/getting-started.md
Labels: 8.x, Needs backport

#1632 Make getRow() method description visible in Algolia
  development/components/database/db.md
Labels: 8.x

#1630 Add hooklisturl variable in firstsection to be able to personalize future V9 search for hooks
  _index.md
Labels: 8.x

#1631 Create documentation about Link component
  development/components/link.md
  development/components/smarty-extensions/_index.md
Labels: 8.x

#1634 FormHelper, HelperTable search requests tags
  development/components/helpers/helperform.md
Labels: 8.x

#1636 Add example of placeholders in translation
  modules/creation/module-translation/new-system.md
Labels: 8.x
