Repository PrestaShop/docs, pull requests merged in 2023-05, with the labels that each got.

#1655 Add missing color-column reference
  development/components/grid/columns-reference/_index.md
Labels: 1.7.x

#1657 Remove reference to new product page on 8.0, because documented in 8.1 changes
  modules/core-updates/8.0.md
Labels: 8.x

#1662 Add CONTRIBUTION_PROCESS.md
  .github/CONTRIBUTION_PROCESS.md
Labels: 8.x

#1663 Fix a link to the moduleroutes demo module
  modules/concepts/hooks/list-of-hooks/moduleRoutes.md
Labels: 8.x

#1664 PHP compatibility for PrestaShop 8.1
  basics/installation/system-requirements.md
Labels: 8.x

#1668 Improve Link Component & generate admin links
  development/components/link.md
  modules/concepts/controllers/admin-controllers/route-generation.md
Labels: 8.x

#1656 Create variables.md
  modules/creation/displaying-content-in-front-office.md
  themes/reference/templates/variables.md
Labels: 8.x

#1670 Update apache version
  basics/installation/system-requirements.md
Labels: 8.x

#1671 Redirect security policy
  project/img/security-process.png
  project/security-policy.md
Labels: 8.x

#1672 Redirect security policy
  project/img/security-process.png
  project/security-policy.md
Labels: 1.7.x, Backported
