Repository PrestaShop/docs, pull requests merged in 2024-07, with the labels that each got.

#1840 Replace expired link (Fatcow icon)
  modules/creation/tutorial.md
Labels: 9.x

#1839 Replace expired link (Fatcow icon)
  modules/creation/tutorial.md
Labels: 8.x

#1844 Update upgrade.md
  basics/keeping-up-to-date/upgrade.md
Labels: 1.7.x

#1845 Stop using minversion in the heading
  themes/getting-started/theme-yml.md
Labels: 8.x, Add to v9 docs

#1847 Add post-update-checklist part (v8)
  basics/keeping-up-to-date/upgrade-module/post-update-checklist.md
Labels: 8.x

#1848 Add post-update-checklist part (v9)
  basics/keeping-up-to-date/upgrade-module/post-update-checklist.md
Labels: 9.x

#1850 Add post-restore-checklist part
  basics/keeping-up-to-date/upgrade-module/post-restore-checklist.md
Labels: 9.x
