Repository PrestaShop/docs, pull requests merged in 2024-06, with the labels that each got.

#1822 Document all breaking changes and notable changes in PrestaShop V9
  modules/core-updates/9.0.md
Labels: 9.x

#1824 Update php-ps-info screenshot for v8
  basics/installation/img/phppsinfo.jpg
  basics/installation/img/phppsinfo.png
  basics/installation/system-requirements.md
Labels: 8.x

#1826 EntitySearchInput is available since PS 8.1.7
  development/components/global-components.md
Labels: 9.x

#1825 EntitySearchInput available from PS 8.1.7
  development/components/global-components.md
Labels: 8.x

#1823 Detail the new login migration impacts
  modules/core-updates/9.0.md
Labels: 9.x

#1808 Module Multistore - Correct description, more readable code
  modules/concepts/multistore.md
Labels: 1.7.x

#1827 Explain new Symfony kernel split
  modules/core-updates/9.0.md
Labels: 9.x

#1830 [doc] - improve 'How to override Back Office views' guide in admin-views.md
  modules/concepts/templating/admin-views.md
Labels: 8.x, Add to v9 docs

#1831 Update misleading create-custom-column-type.md
  development/components/grid/tutorials/create-custom-column-type.md
Labels: 8.x, Add to v9 docs

#1828 Document context refacto and modifications regarding symfony controllers
  modules/core-updates/9.0.md
Labels: 9.x

#1829 Detail the impacts of the new Symfony layout
  modules/core-updates/9.0.md
Labels: 9.x

#1837 Added info about mariadb campaign
  contribute/contribution-guidelines/ui-tests.md
Labels: 9.x

#1836 Add v9 in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 8.x

#1832 Mail SSL encryption was dropped
  modules/core-updates/9.0.md
Labels: 9.x
