Repository PrestaShop/docs, pull requests merged in 2024-11, with the labels that each got.

#1874 Update how-to-create-your-own-behat-tests.md
  testing/integration-tests/how-to-create-your-own-behat-tests.md
Labels: 8.x

#1873 Update how-to-create-your-own-behat-tests.md
  testing/integration-tests/how-to-create-your-own-behat-tests.md
Labels: 8.x

#1882 Add missing argument
  development/components/console/prestashop-update-sql-upgrade-file-hooks-listing.md
Labels: 9.x

#1881 Add missing argument
  development/components/console/prestashop-update-sql-upgrade-file-hooks-listing.md
Labels: 8.x

#1879 Annotation to attribute
  modules/concepts/controllers/admin-controllers/_index.md
Labels: 9.x

#1878 Update additional-action-buttons.md
  modules/sample-modules/order-pages-new-hooks/additional-action-buttons.md
Labels: 8.x, Add to v9 docs

#1875 Update httpd.md to include FilesMatch example for PHP-FPM in other container with different mount path
  basics/installation/advanced/httpd.md
Labels: 8.x

#1884 Update MySQL minimum requirement for V1.7
  basics/installation/system-requirements.md
Labels: 1.7.x

#1883 Update MySQL and MariaBD minimum requirements for V8
  basics/installation/system-requirements.md
Labels: 8.x

#1885 Update MySQL minimum requirement for V9
  basics/installation/system-requirements.md
Labels: 9.x

#1892 Update prefix table information
  development/database/_index.md
Labels: 9.x

#1890 Add missing MariaDB information
  basics/installation/system-requirements.md
Labels: 9.x

#1891 Update Docker vars
  basics/installation/environments/docker.md
Labels: 9.x

#1888 Update MySQL documentation link for V9
  basics/installation/_index.md
Labels: 9.x

#1886 Update MySQL documentation link for V8
  basics/installation/_index.md
Labels: 8.x

#1872 Supported branches improvements + hooks in patch versions
  contribute/contribution-guidelines/supported-branches.md
Labels: 9.x
