Repository PrestaShop/docs, pull requests merged in 2024-12, with the labels that each got.

#1896 Add PHP 8.4 in compatibility chart
  basics/installation/system-requirements.md
Labels: 9.x

#1897 docs: fix docker image tag displayed
  basics/installation/environments/docker.md
Labels: 8.x

#1894 Update shape color names in content
  development/architecture/introduction.md
Labels: 8.x, Add to v9 docs

#1898 Improve how to add a core hook page
  development/components/hook/register-new-hook.md
Labels: 8.x

#1900 Add hook contributions DoR
  contribute/contribute-pull-requests/add_hook.md
  development/components/hook/register-new-hook.md
Labels: 8.x

#1901 Remove manual upgrade part
  basics/keeping-up-to-date/img/image38.png
  basics/keeping-up-to-date/upgrade.md
Labels: 8.x

#1904 Add missing composer require commands as somes packages of php-dev-tools are suggestions instead of requirements
  modules/testing/advanced-checks.md
  modules/testing/basic-checks.md
Labels: 9.x

#1903 Add missing composer require commands as somes packages of php-dev-tools are suggestions instead of requirements
  modules/testing/advanced-checks.md
  modules/testing/basic-checks.md
Labels: 8.x

#1905 Update tools-for-theme-designers.md
  themes/getting-started/tools-for-theme-designers.md
Labels: 8.x

#1906 Update tools-for-theme-designers.md
  themes/getting-started/tools-for-theme-designers.md
Labels: 8.x, Add to v9 docs

#1907 Change the version of prestashop in the link for v8
  modules/concepts/controllers/admin-controllers/_index.md
Labels: 8.x, Version specific
