Repository PrestaShop/docs, pull requests merged in 2024-10, with the labels that each got.

#1868 Add cron task to update the documentation API JSON file
  .github/workflows/update-api.yml
Labels: 9.x

#1869 Update Node requirement in the doc for 9.0
  basics/installation/_index.md
  basics/installation/system-requirements.md
  development/coding-standards/_index.md
  development/compile-assets.md
  modules/core-updates/9.0.md
  themes/getting-started/asset-management/webpack.md
Labels: 9.x

#1867 Update upgrade.md
  basics/keeping-up-to-date/upgrade.md
Labels: 8.x

#1866 Update upgrade.md: Better copy command
  basics/keeping-up-to-date/upgrade.md
Labels: 1.7.x

#1870 Fix CSS variable naming typo
  development/ui-kit/variables-reference.md
Labels: 9.x

#1871 Add the update API workflow into the default branch
  .github/workflows/update-api.yml
Labels: 8.x

#1821 Add upgrade module contribution part
  contribute/contribution-guidelines/pull-requests.md
  contribute/contribution-guidelines/upgrade-module.md
  contribute/contribution-process/how-pull-requests-are-processed.md
  contribute/img/needs-autoupgrade-pr-label.png
Labels: 9.x
