Repository PrestaShop/docs, pull requests merged in 2025-02, with the labels that each got.

#1919 docs: add additional informations about FQCN services
  modules/concepts/services/_index.md
Labels: 8.x, Add to v9 docs

#1908 Updates for the notable changes page
  modules/core-updates/9.0.md
Labels: 9.x

#1915 Update nginx.md - fixes the issue with addons installation timeout
  basics/installation/nginx.md
Labels: 1.7.x, Add to v9 docs

#1889 Remove impossible Ping
  contribute/contribute-pull-requests/add_hook.md
Labels: 8.x, Add to v9 docs

#1895 Fix Typo in phpMyAdmin example
  basics/installation/environments/docker.md
Labels: 8.x
