Repository PrestaShop/docs, pull requests merged in 2025-04, with the labels that each got.

#1951 Checkout the repo with token to get proper permissions right away
  .github/workflows/update-api.yml
Labels: 9.x

#1950 Checkout the repo with token to get permissions right away
  .github/workflows/update-api.yml
Labels: 8.x

#1841 feat: update module autoupgrade name to Update assistant
  basics/keeping-up-to-date/use-autoupgrade-module.md
  contribute/contribution-guidelines/pull-requests.md
  development/architecture/file-structure/_index.md
  development/architecture/introduction.md
Labels: 1.7.x, Blocked

#1843 feat: update module autoupgrade name to Update assistant
  basics/keeping-up-to-date/use-autoupgrade-module.md
  contribute/contribution-guidelines/pull-requests.md
  development/architecture/file-structure/_index.md
  development/components/hook/register-new-hook.md
Labels: Blocked, 9.x

#1842 feat: update module autoupgrade name to Update assistant
  contribute/contribution-guidelines/pull-requests.md
  development/architecture/file-structure/_index.md
  development/components/hook/register-new-hook.md
Labels: 8.x

#1953 Update tutorial.md
  modules/creation/tutorial.md
Labels: 8.x

#1952 Update module-file-structure.md
  modules/creation/module-file-structure.md
Labels: 8.x, Add to v9 docs

#1944 Parameters content update
  modules/concepts/hooks/list-of-hooks/actionOrderSlipAdd.md
Labels: 8.x, Add to v9 docs

#1954 Refresh Update FAQ and add explanation about why a release could be missing from Update Assistant
  faq/upgrade.md
Labels: improvement, 8.x

#1956 Refresh Update FAQ and add explanation about why a release could be missing from Update Assistant
  faq/upgrade.md
Labels: improvement, 9.x

#1958 Add details about where to download the zip and xml of PrestaShop for update
  basics/keeping-up-to-date/update/update-from-the-back-office.md
  basics/keeping-up-to-date/update/update-from-the-cli.md
Labels: improvement, 1.7.x

#1959 Add details about where to download the zip and xml of PrestaShop for update
  basics/keeping-up-to-date/update/update-from-the-back-office.md
  basics/keeping-up-to-date/update/update-from-the-cli.md
Labels: improvement, 9.x

#1963 Post update checklist - 1.7.x
  basics/keeping-up-to-date/update/post-update-checklist.md
Labels: 1.7.x

#1964 Post update checklist - 8.x
  basics/keeping-up-to-date/update/post-update-checklist.md
Labels: 8.x

#1965 Post update checklist - 9.x
  basics/keeping-up-to-date/update/post-update-checklist.md
Labels: 9.x

#1966 Adapt example-modules GitHub URL to new branch strategy
  development/components/form/_index.md
  development/components/form/types-reference/navigation-tab-type.md
  development/components/global-components.md
  development/components/mail-templates/_index.md
  modules/concepts/commands.md
  modules/concepts/doctrine/_index.md
  modules/concepts/doctrine/how-to-handle-multi-lang-doctrine-entity.md
  modules/concepts/hooks/list-of-hooks/action<DefinitionId>GridDefinitionModifier.md
  modules/concepts/hooks/list-of-hooks/action<DefinitionId>GridQueryBuilderModifier.md
  modules/concepts/hooks/list-of-hooks/action<FormName>FormBuilderModifier.md
  modules/concepts/hooks/list-of-hooks/action<FormName>FormDataProviderData.md
  modules/concepts/hooks/list-of-hooks/action<FormName>FormDataProviderDefaultData.md
  modules/concepts/hooks/list-of-hooks/actionAdminControllerSetMedia.md
  modules/concepts/hooks/list-of-hooks/actionAfterCreate<FormName>FormHandler.md
  modules/concepts/hooks/list-of-hooks/actionAfterUpdate<FormName>FormHandler.md
  modules/concepts/hooks/list-of-hooks/actionBuildMailLayoutVariables.md
  modules/concepts/hooks/list-of-hooks/actionGetAdminOrderButtons.md
  modules/concepts/hooks/list-of-hooks/actionGetMailLayoutTransformations.md
  modules/concepts/hooks/list-of-hooks/actionListMailThemes.md
  modules/concepts/hooks/list-of-hooks/displayAdminOrder.md
  modules/concepts/hooks/list-of-hooks/displayAdminOrderMain.md
  modules/concepts/hooks/list-of-hooks/displayAdminOrderSideBottom.md
  modules/concepts/hooks/list-of-hooks/displayAdminOrderTabContent.md
  modules/concepts/hooks/list-of-hooks/displayAdminOrderTabLink.md
  modules/concepts/hooks/list-of-hooks/displayAdminOrderTop.md
  modules/concepts/hooks/list-of-hooks/displayAdminProductsExtra.md
  modules/concepts/hooks/list-of-hooks/displayAdminProductsQuantitiesStepBottom.md
  modules/concepts/hooks/list-of-hooks/displayFooterBefore.md
  modules/concepts/hooks/list-of-hooks/displayProductExtraContent.md
  modules/concepts/hooks/list-of-hooks/moduleRoutes.md
  modules/concepts/overrides.md
  modules/concepts/webservice/_index.md
  modules/creation/adding-configuration-page-modern.md
  modules/sample-modules/_index.md
  modules/sample-modules/extend-product-page.md
  modules/sample-modules/extending-sf-form-with-upload-image-field.md
  modules/sample-modules/order-pages-new-hooks/additional-action-buttons.md
  modules/sample-modules/order-pages-new-hooks/signature-widget.md
Labels: 8.x

#1969 Update actionFilterDeliveryOptionList.md
  modules/concepts/hooks/list-of-hooks/actionFilterDeliveryOptionList.md
Labels: 8.x

#1970 Update displayBeforeCarrier.md
  modules/concepts/hooks/list-of-hooks/displayBeforeCarrier.md
Labels: 8.x, Add to v9 docs
