Repository PrestaShop/docs, pull requests merged in 2025-05, with the labels that each got.

#1973 Specify from where Update Assistant commands must be run
  basics/keeping-up-to-date/update/update-from-the-cli.md
Labels: 9.x

#1972 Specify from where Update Assistant commands must be run
  basics/keeping-up-to-date/update/update-from-the-cli.md
Labels: 1.7.x

#1971 Specify from where Update Assistant commands must be run (Branch 8.x)
  basics/keeping-up-to-date/update/update-from-the-cli.md
Labels: 8.x

#1976 fix: add missing $ symbol
  development/architecture/migration-guide/forms/CRUD-forms.md
Labels: 9.x

#1975 fix: add missing $ symbol
  development/architecture/migration-guide/forms/CRUD-forms.md
Labels: 8.x

#1974 fix: add missing $ symbol
  development/architecture/migration-guide/forms/CRUD-forms.md
Labels: 1.7.x
