Repository PrestaShop/docs, pull requests merged in 2025-01, with the labels that each got.

#1909 Update Apache Httpd example
  basics/installation/advanced/httpd.md
Labels: 8.x, Add to v9 docs

#1912 Allow .well-known folder on Nginx
  basics/installation/advanced/nginx.md
Labels: 9.x

#1910 Allow .well-known folder on Nginx
  basics/installation/advanced/nginx.md
Labels: 8.x

#1913 Allow .well-known folder on Nginx
  basics/installation/nginx.md
Labels: 1.7.x

#1918 [UPGRADE] Add section for CLI, improve upgrade page
  basics/keeping-up-to-date/upgrade-module/_index.md
  basics/keeping-up-to-date/upgrade-module/upgrade-cli.md
  basics/keeping-up-to-date/upgrade.md
Labels: 1.7.x
