Repository PrestaShop/docs, pull requests merged in 2025-06, with the labels that each got.

#1977 feat: add type options to DatePickerType
  development/components/form/types-reference/date-picker.md
Labels: 1.7.x

#1978 feat: add type options to DatePickerType
  development/components/form/types-reference/date-picker.md
Labels: 8.x

#1984 modules mail theme add layout change path of layout replace __DIR__ b…
  modules/concepts/mail-templates/add-a-layout-from-module.md
Labels: 8.x, Add to v9 docs

#1988 Fix API block and minor changes in the requirements
  admin-api/_index.md
  admin-api/context.md
  admin-api/how-to-use.md
  admin-api/oauth.md
  admin-api/swagger-doc/_index.md
  basics/installation/system-requirements.md
Labels: 9.x

#1990 Remove notice about feature in development
  admin-api/how-to-use.md
Labels: 9.x

#1991 Fix SVG path on page /admin-api/api-platform/
  admin-api/resource_server/api-platform.md
Labels: 9.x

#2000 Update PHP recommend version
  basics/installation/system-requirements.md
Labels: 9.x
